[package]
authors.workspace      = true
description            = "Miden remote prover"
edition.workspace      = true
homepage.workspace     = true
keywords               = ["miden", "prover", "remote"]
license.workspace      = true
name                   = "miden-remote-prover"
readme                 = "README.md"
repository.workspace   = true
rust-version.workspace = true
version.workspace      = true

[lints]
workspace = true

[dependencies]
anyhow                 = { workspace = true }
async-trait            = { version = "0.1" }
clap                   = { features = ["env"], workspace = true }
http                   = { workspace = true }
humantime              = { workspace = true }
miden-block-prover     = { workspace = true }
miden-node-proto       = { workspace = true }
miden-node-proto-build = { features = ["internal"], workspace = true }
miden-node-utils       = { workspace = true }
miden-protocol         = { features = ["std"], workspace = true }
miden-tx               = { features = ["concurrent", "std"], workspace = true }
miden-tx-batch-prover  = { features = ["std"], workspace = true }
opentelemetry          = { version = "0.31" }
prost                  = { default-features = false, features = ["derive"], workspace = true }
tokio                  = { features = ["full"], workspace = true }
tokio-stream           = { features = ["net"], version = "0.1" }
tonic                  = { default-features = false, features = ["codegen", "router", "transport"], version = "0.14" }
tonic-health           = { version = "0.14" }
tonic-prost            = { workspace = true }
tonic-reflection       = { workspace = true }
tonic-web              = { version = "0.14" }
tower-http             = { features = ["trace"], workspace = true }
tracing                = { workspace = true }

[dev-dependencies]
assert_matches  = { workspace = true }
miden-protocol  = { features = ["testing"], workspace = true }
miden-standards = { features = ["testing"], workspace = true }
miden-testing   = { workspace = true }
miden-tx        = { features = ["testing"], workspace = true }

[build-dependencies]
fs-err                             = { workspace = true }
miden-node-proto-build             = { features = ["internal"], workspace = true }
miden-node-rocksdb-cxx-linkage-fix = { workspace = true }
miette                             = { features = ["fancy"], version = "7.5" }
tonic-prost-build                  = { workspace = true }

[package.metadata.cargo-machete]
ignored = [
  "http",
  "prost",
  "tonic-prost", # used in generated OUT_DIR code
]
